name: stay_tuned
description: "Stay Tuned (Waitlist registration) feature"
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core
  networking:
    path: ../../networking
  design_system:
    path: ../../design_system
  localization:
    path: ../../localization
  flutter_bloc: ^9.1.1
  country_code_picker: ^3.4.1
