name: localization
description: "App translations and localizations"
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  country_code_picker: ^3.4.1

flutter:
  generate: true
