name: core
description: "Core utility and failure contracts"
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  get_it: ^8.2.0
  injectable: ^2.5.1
  localization:
    path: ../localization
